name: C/C++ CI

on:
  push:
    branches: [ "main", "eval", "parser", "tokenizer" ]
  pull_request:
    branches: [ "main", "eval", "parser", "tokenizer" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: make
      run: make
    - name: all tests
      run: cd scripts && ./allTests.sh
